# - Try to find KMSOPENCVPLUGINSAMPLE library

#=============================================================================
# Copyright 2014 Kurento
#
#=============================================================================

set(PACKAGE_VERSION "0.0.1~12.gd26e75d")
set(KMSOPENCVPLUGINSAMPLE_VERSION ${PACKAGE_VERSION})

message (STATUS "Looking for KMSOPENCVPLUGINSAMPLE: 0.0.1~12.gd26e75d")

include (GenericFind)

generic_find (
  REQUIRED
  LIBNAME KMSCORE
  VERSION ^6.0.0
)

generic_find (
  REQUIRED
  LIBNAME KMSELEMENTS
  VERSION ^6.0.0
)

generic_find (
  REQUIRED
  LIBNAME KMSFILTERS
  VERSION ^6.0.0
)

set (REQUIRED_VARS
  KMSOPENCVPLUGINSAMPLE_VERSION
  KMSOPENCVPLUGINSAMPLE_INCLUDE_DIRS
  KMSOPENCVPLUGINSAMPLE_LIBRARY
  KMSOPENCVPLUGINSAMPLE_LIBRARIES
)

set(KMSOPENCVPLUGINSAMPLE_INCLUDE_DIRS
  ${KMSCORE_INCLUDE_DIRS}
  ${KMSELEMENTS_INCLUDE_DIRS}
  ${KMSFILTERS_INCLUDE_DIRS}
)

if (NOT "OpencvPluginSample.hpp OpencvPluginSampleInternal.hpp" STREQUAL " ")
  find_path(KMSOPENCVPLUGINSAMPLE_INTERFACE_INCLUDE_DIR
    NAMES
      OpencvPluginSample.hpp
      OpencvPluginSampleInternal.hpp
    PATH_SUFFIXES
      build/src/server/interface/generated-cpp
      kurento/modules/opencvpluginsample
  )

  list (APPEND KMSOPENCVPLUGINSAMPLE_INCLUDE_DIRS ${KMSOPENCVPLUGINSAMPLE_INTERFACE_INCLUDE_DIR})
  list (APPEND REQUIRED_VARS KMSOPENCVPLUGINSAMPLE_INTERFACE_INCLUDE_DIR)
endif ()

if (NOT "OpencvPluginSampleImplFactory.hpp" STREQUAL "")
  find_path(KMSOPENCVPLUGINSAMPLE_IMPLEMENTATION_INTERNAL_INCLUDE_DIR
    NAMES
      OpencvPluginSampleImplFactory.hpp
    PATH_SUFFIXES
      build/src/server/implementation/generated-cpp
      kurento/modules/opencvpluginsample
  )

  list (APPEND KMSOPENCVPLUGINSAMPLE_INCLUDE_DIRS ${KMSOPENCVPLUGINSAMPLE_IMPLEMENTATION_INTERNAL_INCLUDE_DIR})
  list (APPEND REQUIRED_VARS KMSOPENCVPLUGINSAMPLE_IMPLEMENTATION_INTERNAL_INCLUDE_DIR)
endif ()

if (NOT "OpencvPluginSampleOpenCVImpl.hpp OpencvPluginSampleImpl.hpp" STREQUAL "")
  find_path(KMSOPENCVPLUGINSAMPLE_IMPLEMENTATION_GENERATED_INCLUDE_DIR
    NAMES
      OpencvPluginSampleOpenCVImpl.hpp OpencvPluginSampleImpl.hpp
    PATH_SUFFIXES
      src/server/implementation/objects
      kurento/modules/opencvpluginsample
  )

  list (APPEND KMSOPENCVPLUGINSAMPLE_INCLUDE_DIRS ${KMSOPENCVPLUGINSAMPLE_IMPLEMENTATION_GENERATED_INCLUDE_DIR})
  list (APPEND REQUIRED_VARS KMSOPENCVPLUGINSAMPLE_IMPLEMENTATION_GENERATED_INCLUDE_DIR)
endif()

if (NOT "" STREQUAL "")
  find_path(KMSOPENCVPLUGINSAMPLE_IMPLEMENTATION_EXTRA_INCLUDE_DIR
    NAMES
      
    PATH_SUFFIXES
      
      kurento/modules/opencvpluginsample
  )

  list (APPEND KMSOPENCVPLUGINSAMPLE_INCLUDE_DIRS ${KMSOPENCVPLUGINSAMPLE_IMPLEMENTATION_EXTRA_INCLUDE_DIR})
  list (APPEND REQUIRED_VARS KMSOPENCVPLUGINSAMPLE_IMPLEMENTATION_EXTRA_INCLUDE_DIR)
endif ()

if (NOT "" STREQUAL "")
  find_path(KMSOPENCVPLUGINSAMPLE_INTERFACE_EXTRA_INCLUDE_DIR
    NAMES
      
    PATH_SUFFIXES
      
      kurento/modules/opencvpluginsample
  )

  list (APPEND KMSOPENCVPLUGINSAMPLE_INCLUDE_DIRS ${KMSOPENCVPLUGINSAMPLE_INTERFACE_EXTRA_INCLUDE_DIR})
  list (APPEND REQUIRED_VARS KMSOPENCVPLUGINSAMPLE_INTERFACE_EXTRA_INCLUDE_DIR)
endif ()

find_library (KMSOPENCVPLUGINSAMPLE_LIBRARY
  NAMES
    kmsopencvpluginsampleimpl
  PATH_SUFFIXES
    build/src/server
)

set (REQUIRED_LIBS "")
foreach (LIB ${REQUIRED_LIBS})
  string(FIND ${LIB} " " POS)

  if (${POS} GREATER 0)
    string(REPLACE " " ";" REQUIRED_LIB_LIST ${LIB})
    include (CMakeParseArguments)
    cmake_parse_arguments("PARAM" "" "LIBNAME" "" ${REQUIRED_LIB_LIST})

    if (DEFINED PARAM_LIBNAME)
      generic_find (${REQUIRED_LIB_LIST} REQUIRED)
      set (LIB_NAME ${PARAM_LIBNAME})
    else()
      string (SUBSTRING ${LIB} 0 ${POS} LIB_NAME)
      string (SUBSTRING ${LIB} ${POS} -1 LIB_VERSION)
      string (STRIP ${LIB_NAME} LIB_NAME)
      string (STRIP ${LIB_VERSION} LIB_VERSION)
      generic_find (LIBNAME ${LIB_NAME} REQUIRED VERSION "${LIB_VERSION}")
    endif()
  else ()
    string (STRIP ${LIB} LIB_NAME)
    generic_find (LIBNAME ${LIB_NAME} REQUIRED)
  endif ()
  list (APPEND REQUIRED_LIBRARIES ${${LIB_NAME}_LIBRARIES})
  list (APPEND KMSOPENCVPLUGINSAMPLE_INCLUDE_DIRS ${${LIB_NAME}_INCLUDE_DIRS})

endforeach()

set(KMSOPENCVPLUGINSAMPLE_INCLUDE_DIRS
  ${KMSOPENCVPLUGINSAMPLE_INCLUDE_DIRS}
  CACHE INTERNAL "Include directories for KMSOPENCVPLUGINSAMPLE library"
)

set (KMSOPENCVPLUGINSAMPLE_LIBRARIES
  ${KMSOPENCVPLUGINSAMPLE_LIBRARY}
  ${KMSCORE_LIBRARIES}
  ${KMSELEMENTS_LIBRARIES}
  ${KMSFILTERS_LIBRARIES}
  ${REQUIRED_LIBRARIES}
  CACHE INTERNAL "Libraries for KMSOPENCVPLUGINSAMPLE"
)

include (FindPackageHandleStandardArgs)

find_package_handle_standard_args(KMSOPENCVPLUGINSAMPLE
  FOUND_VAR
    KMSOPENCVPLUGINSAMPLE_FOUND
  REQUIRED_VARS
    ${REQUIRED_VARS}
  VERSION_VAR
    KMSOPENCVPLUGINSAMPLE_VERSION
)

mark_as_advanced(
  KMSOPENCVPLUGINSAMPLE_FOUND
  KMSOPENCVPLUGINSAMPLE_VERSION
  KMSOPENCVPLUGINSAMPLE_INTERFACE_INCLUDE_DIR
  KMSOPENCVPLUGINSAMPLE_IMPLEMENTATION_INTERNAL_INCLUDE_DIR
  KMSOPENCVPLUGINSAMPLE_IMPLEMENTATION_GENERATED_INCLUDE_DIR
  KMSOPENCVPLUGINSAMPLE_IMPLEMENTATION_EXTRA_INCLUDE_DIR
  KMSOPENCVPLUGINSAMPLE_INTERFACE_EXTRA_INCLUDE_DIR
  KMSOPENCVPLUGINSAMPLE_INCLUDE_DIRS
  KMSOPENCVPLUGINSAMPLE_LIBRARY
  KMSOPENCVPLUGINSAMPLE_LIBRARIES
)
