/* Autogenerated with kurento-module-creator */

#include <iostream>
#include "OpencvPluginSampleInternal.hpp"
#include <KurentoException.hpp>
#include <jsonrpc/JsonSerializer.hpp>
#include "MediaPipeline.hpp"

namespace kurento
{
namespace module
{
namespace opencvpluginsample
{

void OpencvPluginSampleMethodSetFilterType::invoke (std::shared_ptr<OpencvPluginSample> obj)
{
  if (!obj) {
    throw KurentoException (MEDIA_OBJECT_NOT_FOUND, "Invalid object while invoking method OpencvPluginSample::setFilterType");
  }

  return obj->setFilterType (filterType);
}

void OpencvPluginSampleMethodSetFilterType::Serialize (kurento::JsonSerializer &s)
{
  if (s.IsWriter) {
    s.SerializeNVP (filterType);

  } else {
    if (s.JsonValue.isNull ()) {
      throw KurentoException (MARSHALL_ERROR,
                              "'operationParams' is required");
    } else if (!s.JsonValue.isObject ()){
      throw KurentoException (MARSHALL_ERROR,
                              "'operationParams' should be an object");
    }

    if (!s.JsonValue.isMember ("filterType") || !s.JsonValue["filterType"].isConvertibleTo (Json::ValueType::intValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'filterType' parameter should be a integer");
    }

    s.SerializeNVP (filterType);

  }
}

void OpencvPluginSampleMethodSetEdgeThreshold::invoke (std::shared_ptr<OpencvPluginSample> obj)
{
  if (!obj) {
    throw KurentoException (MEDIA_OBJECT_NOT_FOUND, "Invalid object while invoking method OpencvPluginSample::setEdgeThreshold");
  }

  return obj->setEdgeThreshold (edgeValue);
}

void OpencvPluginSampleMethodSetEdgeThreshold::Serialize (kurento::JsonSerializer &s)
{
  if (s.IsWriter) {
    s.SerializeNVP (edgeValue);

  } else {
    if (s.JsonValue.isNull ()) {
      throw KurentoException (MARSHALL_ERROR,
                              "'operationParams' is required");
    } else if (!s.JsonValue.isObject ()){
      throw KurentoException (MARSHALL_ERROR,
                              "'operationParams' should be an object");
    }

    if (!s.JsonValue.isMember ("edgeValue") || !s.JsonValue["edgeValue"].isConvertibleTo (Json::ValueType::intValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'edgeValue' parameter should be a integer");
    }

    s.SerializeNVP (edgeValue);

  }
}

std::shared_ptr<MediaPipeline> OpencvPluginSampleConstructor::getMediaPipeline ()
{
  return mediaPipeline;
}

void OpencvPluginSampleConstructor::Serialize (kurento::JsonSerializer &s)
{
  if (s.IsWriter) {
    s.SerializeNVP (mediaPipeline);

  } else {
    if (s.JsonValue.isNull ()) {
      throw KurentoException (MARSHALL_ERROR,
                              "'constructorParams' is required");
    } else if (!s.JsonValue.isObject ()){
      throw KurentoException (MARSHALL_ERROR,
                              "'constructorParams' should be an object");
    }

    if (!s.JsonValue.isMember ("mediaPipeline") || !s.JsonValue["mediaPipeline"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'mediaPipeline' parameter should be a string");
    }

    s.SerializeNVP (mediaPipeline);

  }
}

} /* opencvpluginsample */
} /* module */
} /* kurento */
