/* Autogenerated with kurento-module-creator */

#ifndef __OPENCV_PLUGIN_SAMPLE_INTERNAL_HPP__
#define __OPENCV_PLUGIN_SAMPLE_INTERNAL_HPP__

#include "OpencvPluginSample.hpp"

namespace kurento
{
class JsonSerializer;
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
namespace module
{
namespace opencvpluginsample
{

class OpencvPluginSampleMethodSetFilterType
{
public:
  OpencvPluginSampleMethodSetFilterType() {}
  ~OpencvPluginSampleMethodSetFilterType() {}

  void invoke (std::shared_ptr<OpencvPluginSample> obj);
  void Serialize (JsonSerializer &serializer);

  int getFilterType () {
    return filterType;
  }

  void setFilterType (int filterType) {
    this->filterType = filterType;
  }

private:
  int filterType;
};

class OpencvPluginSampleMethodSetEdgeThreshold
{
public:
  OpencvPluginSampleMethodSetEdgeThreshold() {}
  ~OpencvPluginSampleMethodSetEdgeThreshold() {}

  void invoke (std::shared_ptr<OpencvPluginSample> obj);
  void Serialize (JsonSerializer &serializer);

  int getEdgeValue () {
    return edgeValue;
  }

  void setEdgeValue (int edgeValue) {
    this->edgeValue = edgeValue;
  }

private:
  int edgeValue;
};

class OpencvPluginSampleConstructor
{
public:
  OpencvPluginSampleConstructor () {}
  ~OpencvPluginSampleConstructor () {}

  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<MediaPipeline> getMediaPipeline ();

  void setMediaPipeline (std::shared_ptr<MediaPipeline> mediaPipeline) {
    this->mediaPipeline = mediaPipeline;
  }

private:
  std::shared_ptr<MediaPipeline> mediaPipeline;
};

} /* opencvpluginsample */
} /* module */
} /* kurento */

#endif /*  __OPENCV_PLUGIN_SAMPLE_INTERNAL_HPP__ */
